import { StreamVideoProvider } from "@/providers/streamClientProvider";
import { Metadata } from "next";
import React, { ReactNode } from "react";

const RootLayout = ({ children }: { children: ReactNode }) => {
  const metadata: Metadata = {
    title: "Zoom Clone",
    description: "Generated by create next app",
    icons: {
      icon: "/icons/logo.svg",
    },
  };

  return (
    <main>
      <StreamVideoProvider>{children}</StreamVideoProvider>
    </main>
  );
};

export default RootLayout;
